LIR.WEB/Controllers/BenefitController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using LIR.DOMAIN.Entities;
using LIR.INFRASTRUCTURE.Interfaces;
using LIR.VIEWMODEL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LIR.WEB.Controllers
{
    public class BenefitController : Controller
    {
        private readonly IConsumerProfileRepository _consumerProfileRepository;
        private readonly IMapper _mapper;
        private readonly IRetirementSetupRepository _retirementSetupRepository;
        private readonly INotyfService _notyfService;

        public BenefitController(IRetirementSetupRepository retirementSetupRepository,
            IConsumerProfileRepository consumerProfileRepository, IMapper mapper,
            INotyfService notyfService)
        {
            _retirementSetupRepository = retirementSetupRepository;
            _consumerProfileRepository = consumerProfileRepository;
            _mapper = mapper;
            _notyfService = notyfService;
        }
        public IActionResult Request()
        {
            var viewModel = new ConsumerProfileViewModel()
            {
                Birthdate = DateTime.Now,
                ConsumerBenefitResults = new List<ConsumerBenefitResultViewModel>()
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Request(ConsumerProfileViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _consumerProfileRepository.RequestComputation(_mapper.Map<ConsumerProfileViewModel, ConsumerProfile>(viewModel));
                if (result != null)
                {
                    _notyfService.Information("Request Completed");
                    return View(result);
                }
            }
            _notyfService.Warning("Request Failed");
            return View(viewModel);
        }

        public IActionResult RetirementSetup()
        {
            var result = _retirementSetupRepository.GetSetup();
            if (result != null)
            {
                return View(_mapper.Map<RetirementSetup, RetirementSetupViewModel>(result));
            }
            _notyfService.Information("No record found");
            return View(new RetirementSetupViewModel());
        }

        [HttpPost]
        public IActionResult RetirementSetup(RetirementSetupViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var bindModel = _mapper.Map<RetirementSetupViewModel, RetirementSetup>(viewModel);
                var result = viewModel.Id == Guid.Empty ? _retirementSetupRepository.CreateSetup(bindModel) : _retirementSetupRepository.UpdateSetup(bindModel);
                if (result)
                {
                    _notyfService.Information("Request Completed");
                    return View(viewModel);
                }
            }
            _notyfService.Warning("Request Failed");
            return View(viewModel);
        }

        public IActionResult History()
        {
            var viewModel = _consumerProfileRepository.GetAll();
            return View(viewModel);
        }

        public IActionResult HistoryEdit(Guid id)
        {
            var viewModel = _consumerProfileRepository.GetById(id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult HistoryEdit(ConsumerProfileViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _consumerProfileRepository.RequestComputation(_mapper.Map<ConsumerProfileViewModel, ConsumerProfile>(viewModel));
                if (result != null)
                {
                    _notyfService.Information("Request Completed");
                    return View(result);
                }
            }
            _notyfService.Warning("Request Failed");
            return View(viewModel);
        }
    }
}

LIR.WEB/Views/Benefit/History.cshtml
@model IEnumerable<ConsumerProfileViewModel>
@{
    ViewData["Title"] = "History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <h4>History</h4>
        </div>
        <div class="card-body">
            <table id="dtTable" class="table table-bordered">
                <thead>
                    <th></th>
                    <th>Consumer Name</th>
                    <th>Basic Salary</th>
                    <th>Birthdate</th>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="text-align:center;">
                                <a class="btn btn-primary" id="editHistoryBtn" asp-controller="Benefit" asp-action="HistoryEdit" asp-route-id="@item.Id">Edit</a>
                            </td>
                            <td>@item.ConsumerName</td>
                            <td>@item.BasicSalary</td>
                            <td>@item.BirthdateStr</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $('#dtTable').dataTable({});
</script>

LIR.WEB/Views/Benefit/HistoryEdit.cshtml
@model ConsumerProfileViewModel
@{
    ViewData["Title"] = "Request Computation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-lg-9">
    <div class="card">
        <form asp-action="HistoryEdit" asp-controller="Benefit" method="post" id="requestForm">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-12">
                        <h4>Consumer Record</h4>
                    </div>
                </div>
            </div>
            <div class="card-block" style="padding-bottom: 25px;">
                <div class="column">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="container" style="padding-top: 25px;">
                                <div class="col-lg-12">
                                    <label asp-for="ConsumerName"></label>
                                    <input class="form-control" type="text" id="ConsumerName" asp-for="ConsumerName">
                                    <span class="text-danger" asp-validation-for="ConsumerName"></span>
                                </div>
                                <div class="col-lg-12">
                                    <label asp-for="BasicSalary"></label>
                                    <label>Basic Salary</label>
                                    <input class="form-control" min="0" type="number" id="BasicSalary" asp-for="BasicSalary">
                                    <span class="text-danger" asp-validation-for="BasicSalary"></span>
                                </div>
                                <div class="col-lg-12">
                                    <label asp-for="Birthdate"></label>
                                    <label>Birth Date</label>
                                    <input class="form-control" type="date" id="Birthdate" asp-for="Birthdate">
                                    <span class="text-danger" asp-validation-for="Birthdate"></span>
                                </div>
                                @Html.HiddenFor(x => x.ConsumerBenefitResults)
                                @if (Model.ConsumerBenefitResults.Count != 0)
                                {
                                    <hr />
                                    <div class="col-lg-12">
                                        <label> Computation Result </label>
                                        <table class="table table-bordered table-striped table-hover" style="width: 100%;">
                                            <thead>
                                            <th>Multiple</th>
                                            <th>Benefit Amount Quotation</th>
                                            <th>Pended Amount</th>
                                            <th>Benefit</th>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model.ConsumerBenefitResults.OrderBy(x => x.Multiple))
                                                {
                                                    <tr>
                                                        <td>@item.Multiple</td>
                                                        <td>@item.BenefitsAmountQuotation</td>
                                                        <td>@item.PendedAmount</td>
                                                        <td>@item.Benefits</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer" style="text-align: end;">
                <button class="btn btn-success" style="margin-left: 10px;" type="submit" id="submitComputationBtn" onclick="onSubmit()">Re-compute</button>
                <a class="btn btn-danger" asp-controller="Benefit" asp-action="History">Back</a>
            </div>
        </form>
    </div>
</div>

LIR.WEB/Views/Benefit/Request.cshtml
@model ConsumerProfileViewModel
@{
    ViewData["Title"] = "Request Computation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-lg-9">
    <div class="card">
        <form asp-action="Request" asp-controller="Benefit" method="post" id="requestForm">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-12">
                        <h4>Request for Computation</h4>
                    </div>
                </div>
            </div>
            <div class="card-block" style="padding-bottom: 25px;">
                <div class="column">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="container" style="padding-top: 25px;">
                                <div class="col-lg-12">
                                    <label asp-for="ConsumerName"></label>
                                    <input class="form-control" type="text" id="ConsumerName" asp-for="ConsumerName">
                                    <span class="text-danger" asp-validation-for="ConsumerName"></span>
                                </div>
                                <div class="col-lg-12">
                                    <label asp-for="BasicSalary"></label>
                                    <input class="form-control" min="0" type="number" id="BasicSalary" asp-for="BasicSalary">
                                    <span class="text-danger" asp-validation-for="BasicSalary"></span>
                                </div>
                                <div class="col-lg-12">
                                    <label asp-for="Birthdate"></label>
                                    <input class="form-control" type="date" id="Birthdate" asp-for="Birthdate">
                                    <span class="text-danger" asp-validation-for="Birthdate"></span>
                                </div>
                                @Html.HiddenFor(x => x.ConsumerBenefitResults)
                                @if (Model.ConsumerBenefitResults.Count != 0)
                                {
                                    <hr />
                                    <div class="col-lg-12">
                                        <label> Computation Result </label>
                                        <table class="table table-bordered table-striped table-hover" style="width: 100%;">
                                            <thead>
                                            <th>Multiple</th>
                                            <th>Benefit Amount Quotation</th>
                                            <th>Pended Amount</th>
                                            <th>Benefit</th>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model.ConsumerBenefitResults.OrderBy(x => x.Multiple))
                                                {
                                                    <tr>
                                                        <td>@item.Multiple</td>
                                                        <td>@item.BenefitsAmountQuotation</td>
                                                        <td>@item.PendedAmount</td>
                                                        <td>@item.Benefits</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer" style="text-align: end;">
                <a class="btn btn-warning" id="resetFormBtn" asp-controller="Benefit" asp-action="Request">Reset</a>
                <button class="btn btn-success" style="margin-left: 10px;" type="submit" id="submitComputationBtn" onclick="onSubmit()">Compute</button>
            </div>
        </form>
    </div>
</div>

LIR.WEB/Views/Benefit/RetirementSetup.cshtml
@model RetirementSetupViewModel
@{
    ViewData["Title"] = "Retirement Setup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-9">
    <form asp-controller="Benefit" asp-action="RetirementSetup" method="post">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    <h4>Retirement Setup</h4>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    @Html.HiddenFor(x => x.Id)
                    <div class="col-lg-12">
                        <label asp-for="GuaranteedIssue"></label>
                        <input class="form-control" type="number" asp-for="GuaranteedIssue" id="GuaranteedIssue">
                        <span class="text-danger" asp-validation-for="GuaranteedIssue"></span>
                    </div>
                    <div class="col-lg-12">
                        <label asp-for="MaxAgeLimit"></label>
                        <input class="form-control" type="number" asp-for="MaxAgeLimit" id="MaxAgeLimit">
                        <span class="text-danger" asp-validation-for="MaxAgeLimit"></span>
                    </div>
                    <div class="col-lg-12">
                        <label asp-for="MinAgeLimit"></label>
                        <input class="form-control" type="number" asp-for="MinAgeLimit" id="MinAgeLimit">
                        <span class="text-danger" asp-validation-for="MinAgeLimit"></span>
                    </div>
                    <div class="col-lg-12">
                        <label asp-for="MinimumRange"></label>
                        <input class="form-control" type="number" asp-for="MinimumRange" id="MinimumRange">
                        <span class="text-danger" asp-validation-for="MinimumRange"></span>
                    </div>
                    <div class="col-lg-12">
                        <label asp-for="MaximumRange"></label>
                        <input class="form-control" type="number" asp-for="MaximumRange" id="MaximumRange">
                        <span class="text-danger" asp-validation-for="MaximumRange"></span>
                    </div>
                    <div class="col-lg-12">
                        <label asp-for="Increments"></label>
                        <input class="form-control" type="number" asp-for="Increments" id="Increments">
                        <span class="text-danger" asp-validation-for="Increments"></span>
                    </div>
                </div>
            </div>
            <div class="card-footer" style="text-align:end;">
                <button class="btn btn-success" type="submit" id="submitSetupBtn">Submit</button>
            </div>
        </div>
    </form>
</div>

LIR.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LIR - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-responsive-bs/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    @RenderSection("Styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<h4>Life Insurance Retirement</h4>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Benefit" asp-action="Request">Benefit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Benefit" asp-action="History">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Benefit" asp-action="RetirementSetup">Setup</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - LIR.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/font-awesome/js/fontawesome.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>